# Generated by Django 6.0.3 on 2026-03-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consultas', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadística Global',
                'verbose_name_plural': 'Estadísticas Globales',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='default', max_length=100)),
                ('prompt_texto', models.TextField(default='Eres un asistente educativo especializado en programación. Ayuda al usuario a aprender de forma clara y didáctica.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_actualizacion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Prompt',
                'verbose_name_plural': 'Configuraciones de Prompt',
            },
        ),
    ]
